FROM continuumio/miniconda3:4.9.2

LABEL org.opencontainers.image.source https://github.com/icgc-argo-rna-wg/deconvolute-cell-types

ENV PATH="/tools:${PATH}"

COPY *.py /tools/

ENTRYPOINT ["/usr/bin/env"]

CMD ["/bin/bash"]
